title: Supercomputing for AI
description: Foundations, Architectures, and Scaling Deep Learning Workloads
author: Jordi Torres
url: "https://JordiTorresBCN.github.io"
baseurl: "/supercomputing-for-ai-book"

# Ruta logo
logo: "/images/Supercomputing_for_AI_BookCover.png"

remote_theme: just-the-docs/just-the-docs
color_scheme: light

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme

exclude: [Gemfile, Gemfile.lock]
