title: Supercomputing for AI
description: Foundations, Architectures, and Scaling Deep Learning Workloads
author: Jordi Torres
url: "https://JordiTorresBCN.github.io"
baseurl: "/supercomputing-for-ai-book"

# Ruta exacta de tu logo
logo: "assets/images/logo/media/bookCover.jpg"

remote_theme: just-the-docs/just-the-docs
color_scheme: light

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme

exclude: [Chapter01.docx, Chapter12.docx, Titulo.docx, Gemfile, Gemfile.lock, assets/css]
